import * as curves from "./curves/structs";
import * as dsui from "./dsui/structs";
import * as hive from "./hive/structs";
import * as honey from "./honey/structs";
import * as yieldFlow from "./yield-flow/structs";
import {StructClassLoader} from "../_framework/loader";

export function registerClasses(loader: StructClassLoader) { loader.register(honey.Consumption);
loader.register(honey.ConsumptionCondition);
loader.register(honey.HONEY);
loader.register(honey.HoneyTransferred);
loader.register(honey.HoneyUnwrappedToCoin);
loader.register(hive.HIVE);
loader.register(curves.Curved);
loader.register(curves.Stable);
loader.register(curves.Weighted);
loader.register(yieldFlow.DecimalPrecisionForCoinTypesWhitelisted);
loader.register(yieldFlow.DefaultFeeInfo);
loader.register(yieldFlow.DefaultFeeSet);
loader.register(yieldFlow.DeployerCap);
loader.register(yieldFlow.DragonDaoCapability);
loader.register(yieldFlow.DragonFoodCapability);
loader.register(yieldFlow.FeeCollectedForCoin);
loader.register(yieldFlow.FeeCollector);
loader.register(yieldFlow.FeeDistributionPctUpdated);
loader.register(yieldFlow.FeeExtractedForCoin);
loader.register(yieldFlow.FeeInfo);
loader.register(yieldFlow.HiddenWorldCapability);
loader.register(yieldFlow.MasterAccessKey);
loader.register(yieldFlow.NewFeeCollectorKrafted);
loader.register(yieldFlow.PoolFlow);
loader.register(yieldFlow.PoolsConfig);
loader.register(yieldFlow.StableIdentifierAdded);
loader.register(yieldFlow.StableIdentifierRemoved);
loader.register(yieldFlow.ThreeAmmFlowAccess);
loader.register(yieldFlow.TreasuryResourcesDistributed);
loader.register(yieldFlow.TwoAmmFlowAccess);
loader.register(yieldFlow.VoteByVestedTokensCapability);
loader.register(yieldFlow.YieldFlow);
loader.register(dsui.DSUI);
 }
