import * as bee from "./bee/structs";
import * as config from "./config/structs";
import * as curves from "./curves/structs";
import * as dsui from "./dsui/structs";
import * as hiveGems from "./hive-gems/structs";
import {StructClassLoader} from "../_framework/loader";

export function registerClasses(loader: StructClassLoader) { loader.register(bee.BEE);
loader.register(bee.BeesTransferred);
loader.register(bee.BeesUnwrappedToCoin);
loader.register(bee.Burn);
loader.register(bee.BurnCondition);
loader.register(dsui.DSUI);
loader.register(curves.Curved);
loader.register(curves.Stable);
loader.register(curves.Weighted);
loader.register(config.Config);
loader.register(config.BuidlersRoyaltyCollectionAbility);
loader.register(config.DecimalPrecisionForCoinTypesWhitelisted);
loader.register(config.DefaultFeeSet);
loader.register(config.DegenHiveDeployerCap);
loader.register(config.DexDaoCapability);
loader.register(config.FeeCollectedForCoin);
loader.register(config.FeeCollector);
loader.register(config.FeeExtractedForCoin);
loader.register(config.FeeInfo);
loader.register(config.HiveDaoCapability);
loader.register(config.HiveEntryCap);
loader.register(config.NewFeeCollectorKrafted);
loader.register(config.StableIdentifierAdded);
loader.register(config.StableIdentifierRemoved);
loader.register(config.ThreeAmmFeeClaimCapability);
loader.register(config.Treasury);
loader.register(config.TreasuryPercentUpdated);
loader.register(config.TreasuryResourcesDistributed);
loader.register(config.TwoAmmFeeClaimCapability);
loader.register(hiveGems.HiveGemKraftCap);
loader.register(hiveGems.HiveGems);
loader.register(hiveGems.HiveGemsBurnt);
 }
